// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file student.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "student.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool student_serialize_topic(ucdrBuffer* writer, const student* topic)
{
    bool success = true;

        success &= ucdr_serialize_string(writer, topic->name);

        success &= ucdr_serialize_int32_t(writer, topic->number);

        success &= ucdr_serialize_int32_t(writer, topic->grade);

        for(size_t i = 0; i < sizeof(topic->hobby) / 255; ++i)
        {
            success &= ucdr_serialize_string(writer, topic->hobby[i]);
        }
    return success && !writer->error;
}

bool student_deserialize_topic(ucdrBuffer* reader, student* topic)
{
    bool success = true;

        success &= ucdr_deserialize_string(reader, topic->name, 255);

        success &= ucdr_deserialize_int32_t(reader, &topic->number);

        success &= ucdr_deserialize_int32_t(reader, &topic->grade);

        for(size_t i = 0; i < sizeof(topic->hobby) / 255; ++i)
        {
            success &= ucdr_deserialize_string(reader, topic->hobby[i], 255);
        }
    return success && !reader->error;
}

uint32_t student_size_of_topic(const student* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->name) + 1;

        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

        for(size_t i = 0; i < sizeof(topic->hobby) / 255; ++i)
        {
            size += ucdr_alignment(size, 4) + 4 + (uint32_t)strlen(topic->hobby[i]) + 1;
        }
    return size - previousSize;
}
